### ISSUE TITLE
[Nightly] [Linux Mint 17.3] Bugs / Suggestions

### ISSUE THREAD

**Issue by iairpolo** [jaruba/PowderPlayer#111]
First of all, the new UI and the new features are awesome!!!

These are the issues I found:

When I click maximize, it works fine but I get this error:

```
Uncaught TypeError: Cannot read property 'style' of null    ~/.PowderPlayer/resources/app.asar/js/components/Header/actions.js:1
toggleMaximize              @ ~/.PowderPlayer/resources/app.asar/js/components/Header/actions.js:1
action                  @ ~/.PowderPlayer/resources/app.asar/node_modules/alt/lib/actions/index.js:61
ReactErrorUtils.invokeGuardedCallback   @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:71
executeDispatch             @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79
executeDispatchesInOrder        @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102
executeDispatchesAndRelease     @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginHub.js:54
forEachAccumulated          @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23
EventPluginHub.processEventQueue    @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginHub.js:259
runEventQueueInBatch            @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18
ReactEventEmitterMixin.handleTopLevel   @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:34
handleTopLevelWithoutPath       @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventListener.js:93
handleTopLevelImpl          @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventListener.js:73
Mixin.perform               @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/Transaction.js:136
ReactDefaultBatchingStrategy.batchedUpdates @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62
batchedUpdates              @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactUpdates.js:94
ReactEventListener.dispatchEvent    @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventListener.js:204
```

When I'm at the General Settings panel, if I click "Always On Top" it works but I get an error. When I'm not, it works just fine.

```
Uncaught TypeError: Cannot set property 'scrollTop' of null Settings.js:129
componentDidUpdate      @ Settings.js:129assign.notifyAll @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/CallbackQueue.js:65
ON_DOM_READY_QUEUEING.close     @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactReconcileTransaction.js:81
Mixin.closeAll          @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/Transaction.js:202
Mixin.perform           @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/Transaction.js:149
Mixin.perform           @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/Transaction.js:136
assign.perform          @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactUpdates.js:86
flushBatchedUpdates         @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactUpdates.js:147
wrapper             @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactPerf.js:66
Mixin.closeAll          @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/Transaction.js:202
Mixin.perform           @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/Transaction.js:149
ReactDefaultBatchingStrategy.batchedUpdates     @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62
batchedUpdates          @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactUpdates.js:94
ReactEventListener.dispatchEvent    @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventListener.js:204
```

I can't change the color of the subtitles in the General Settings panel. It works fine if I do it once the video is playing on that Settings panel:

```
Uncaught ReferenceError: player is not defined      Settings.js:248
_handleSubColor             @ Settings.js:248onClick @ Settings.js:885
ReactErrorUtils.invokeGuardedCallback   @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:71
executeDispatch             @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:79
executeDispatchesInOrder        @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginUtils.js:102
executeDispatchesAndRelease     @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel     @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginHub.js:54
forEachAccumulated          @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/forEachAccumulated.js:23
EventPluginHub.processEventQueue    @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/EventPluginHub.js:259
runEventQueueInBatch            @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18
ReactEventEmitterMixin.handleTopLevel   @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:34
handleTopLevelWithoutPath       @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventListener.js:93
handleTopLevelImpl          @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventListener.js:73
Mixin.perform               @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/Transaction.js:136
ReactDefaultBatchingStrategy.batchedUpdates     @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62
batchedUpdates              @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactUpdates.js:94
ReactEventListener.dispatchEvent    @ ~/.PowderPlayer/resources/app.asar/node_modules/react/lib/ReactEventListener.js:204
```

In General Settings when click the "Speed Pulsing" toggle I get this:

```
Settings.js:417 Uncaught ReferenceError: PlayerActions is not defined
_handlePulsingToggle                @ Settings.js:417
(anonymous function)                @ Settings.js:142
Polymer.Base._addFeature.fire           @ polymer.html:1280
Polymer.IronButtonStateImpl._userActivate   @ iron-button-state.html:124
Polymer.IronButtonStateImpl._tapHandler     @ iron-button-state.html:109
handler                     @ polymer.html:516
Polymer.Base._addFeature.fire           @ polymer.html:1280
Gestures.fire                   @ polymer.html:852
Gestures.register.forward           @ polymer.html:1149
Gestures.register.click             @ polymer.html:1134
Gestures.handleNative               @ polymer.html:742 
```

Torrent with multiple videos, there's sound but can't see anything. Although, if I click the playlist button and play another video they all work perfectly, even if I change again to the first one. When "File Selector" is on in General Settings, happens the same anyway. Same problem with torrent with one video in it, but I can't make it work from the playlist. Error:

```
~/.PowderPlayer/resources/atom.asar/renderer/api/lib/remote.js:113
Uncaught Error: Could not call remote function `setPosition`. Check that the function signature is correct. Underlying error: Error processing argument 0.
Error: Could not call remote function `setPosition`. Check that the function signature is correct. Underlying error: Error processing argument 0.
    at callFunction (~/.PowderPlayer/resources/atom.asar/browser/lib/rpc-server.js:203:11)
    at EventEmitter.<anonymous> (~/.PowderPlayer/resources/atom.asar/browser/lib/rpc-server.js:293:12)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (~/.PowderPlayer/resources/atom.asar/browser/api/lib/web-contents.js:130:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

While playing a video, click the playlist button I get this (works fine anyways):

```
GET file://~/.PowderPlayer/resources/images/video-placeholder.svg net::ERR_FILE_NOT_FOUND   keyframe-effect-constructor.js:128
b.newUnderlyingAnimationForKeyframeEffect   @   keyframe-effect-constructor.js:128
b.Animation._rebuildUnderlyingAnimation @   web-animations-next-animation.js:86
b.Animation @   web-animations-next-animation.js:35
b.AnimationTimeline._play   @   timeline.js:48
(anonymous function)    @   web-animations-next-animation.js:138
b.Animation._constructChildAnimations   @   web-animations-next-animation.js:137
b.bindAnimationForGroup @   group-constructors.js:197
b.Animation._rebuildUnderlyingAnimation @   web-animations-next-animation.js:91
b.Animation @   web-animations-next-animation.js:35
b.AnimationTimeline._play   @   timeline.js:48
b.AnimationTimeline.play    @   timeline.js:65
Polymer.NeonAnimationRunnerBehaviorImpl._runAnimationEffects    @   neon-animation-runner-behavior.html:62
Polymer.NeonAnimationRunnerBehaviorImpl.playAnimation   @   neon-animation-runner-behavior.html:87
Polymer.hide    @   paper-tooltip.html:291
handler @   polymer.html:516
Polymer.Base._addFeature.fire   @   polymer.html:1280
Gestures.fire   @   polymer.html:852
Gestures.register.forward   @   polymer.html:1149
Gestures.register.click @   polymer.html:1134
Gestures.handleNative   @   polymer.html:742
```

Suggestions:
Make a button for turning back from the Settings and the Playlist panels in video mode (I accidentally closed the app the first time I used it haha).
What happened with the History?
On the settings panel I think there should be a dropdown list instead of up/down arrows when options aren't just increasing/decreasing numbers (e.g. subtitle colors)
In video mode make an option to manually search and select a subtitle

Hope this helps! Cheers!!!

**Comment by jaruba** [comment]
> What happened with the History?

Simplest to answer, Powder Player Nightly is a complete re-write, we just didn't re-make that feature yet. A more complete list of what's still missing can be found here: https://github.com/jaruba/PowderPlayer/issues/108

> Make a button for turning back from the Settings and the Playlist panels in video mode (I accidentally closed the app the first time I used it haha).

Your the second one that clicks the X and expects something else to happen that I know of. (first person that told me expected to get back to the main menu)

I'd make a "Are you sure?" modal when clicking the X.. As for a button to go back from settings / playlist, you just need to click the button that you opened them with. :)

> In video mode make an option to manually search and select a subtitle

Do you mean search between the already found subtitles in the list? Or search on OpenSubtitles manually?

> On the settings panel I think there should be a dropdown list instead of up/down arrows when options aren't just increasing/decreasing numbers (e.g. subtitle colors)

Totally agree, it was like that in some of our initial tests, but the default Material UI drop downs wore very big and wore clipped by the settings container. The current solution is just something I made from scratch, it's not finished, I will make it a drop down too. :)

> While playing a video, click the playlist button I get this (works fine anyways)

That just means that it can't find the default image (if no other image can be found for the playlist items). I'll fix the path for the image.

> Torrent with multiple videos, there's sound but can't see anything. Although, if I click the playlist button and play another video they all work perfectly, even if I change again to the first one.

Does pausing then playing fix the video playback in these cases?

> I can't change the color of the subtitles in the General Settings panel. It works fine if I do it once the video is playing on that Settings panel

Uhm, I think that the `player` object just wasn't initialized yet, I bet it would work if you play something then go back to the main menu.

> Hope this helps! Cheers!!!

It does, thanks a lot! Keep 'em coming if you find more. And sorry for it being such a mess on Linux at the moment.

**Comment by iairpolo** [comment]
> Do you mean search between the already found subtitles in the list? Or search on OpenSubtitles manually?

I mean manually search the file in my PC in case those already found aren't what I need or don't work. But I think manually searching in OpenSubtitles would be even better.

> Does pausing then playing fix the video playback in these cases?

It doesn't :/
If I click next, it works with the following video.

> Uhm, I think that the player object just wasn't initialized yet, I bet it would work if you play something then go back to the main menu.

Sorry, nope

> sorry for it being such a mess on Linux at the moment.

I'm using it to watch my series so don't worry!!!

**Comment by jaruba** [comment]
> I mean manually search the file in my PC in case those already found aren't what I need or don't work. But I think manually searching in OpenSubtitles would be even better.

Ah, you mean browse for a subtitle file. Yeah, that should definitely be in there, you can although drag and drop a subtitle over the video to load it, as that already works.

**Comment by iairpolo** [comment]
> Uhm, I think that the player object just wasn't initialized yet, I bet it would work if you play something then go back to the main menu.

I'll correct my answer. After I played something and back to the main menu, I get the error and the option remains as white. But if play a video again, the color have changed.

Sorry if its hard to understand me. English isn't my native language.

**Comment by jaruba** [comment]
> Sorry if its hard to understand me. English isn't my native language.

I think you explained everything just fine. :)
