### ISSUE TITLE
How can i use electron.exe to open this project?

### ISSUE THREAD

**Issue by AiMaster1010** [jaruba/PowderPlayer#131]
@jaruba hi, i have a question :How can i use electron.exe to open this project? thank you .

**Comment by jaruba** [comment]
did you try following the build instructions from the readme file?

https://github.com/jaruba/PowderPlayer/blob/react-polymer/README.md

**Comment by AiMaster1010** [comment]
@jaruba 
follow the building instructions,i set "npm_config_arch="ia32"" and install npm/ bower/ grunt ,but when i use cmd "C:\Users\YunHai\Desktop\PowderPlayer>electron C:\Users\YunHai\Desktop\PowderPlayer" can not setup powderplayer,there are some errors:
App threw an error during load
C:\Users\YunHai\Desktop\PowderPlayer\src\browser.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buf
fer) { return function (exports, require, module, __filename, __dirname) { import app from 'app';

                                                                           ^^^^^
^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (D:\Program Files\nodejs\node_global\node_modules\electron\dist\resources\default_app.asar\main.js:283:12)
    at Object.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\electron\dist\resources\default_app.asar\main.js:325:5)
    at Object.<anonymous> (D:\Program Files\nodejs\node_global\node_modules\electron\dist\resources\default_app.asar\main.js:361:3)
