### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by karserasl** [jaruba/PowderPlayer#45]
Hello

Im having trouble building it.

```
/root/PowderPlayer/node_modules/pw-wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/src/JsVlcVideo.cpp: In member function ‘v8::Local<v8::Object> JsVlcVideo::deinterlace()’:
/root/PowderPlayer/node_modules/pw-wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/src/JsVlcVideo.cpp:100:67: error: ‘_jsDeinterlace’ was not declared in this scope
     return v8::Local<v8::Object>::New( v8::Isolate::GetCurrent(), _jsDeinterlace );
                                                                   ^
CMakeFiles/WebChimera.js.dir/build.make:54: recipe for target 'CMakeFiles/WebChimera.js.dir/src/JsVlcVideo.cpp.o' failed
make[2]: *** [CMakeFiles/WebChimera.js.dir/src/JsVlcVideo.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/WebChimera.js.dir/all' failed
make[1]: *** [CMakeFiles/WebChimera.js.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
ERR! OMG Process terminated: 2
Unhandled rejection Error: Process terminated: 2
    at ChildProcess.<anonymous> (/root/PowderPlayer/node_modules/pw-wcjs-player/node_modules/wcjs-renderer/node_modules/webchimera.js/node_modules/cmake-js/lib/cMake.js:372:28)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Any ideas?

Thanks

**Comment by jaruba** [comment]
what OS are you using?

**Comment by karserasl** [comment]
Debian Jessie

**Comment by jaruba** [comment]
it looks to me like it's missing the prerequisites (mainly `libvlc-dev`), did you install the build prerequisites for linux?

    sudo apt-get install build-essential cmake libvlc-dev

**Comment by karserasl** [comment]
Yep seems that i did.. 

```
sudo apt-get install build-essential cmake libvlc-dev                                                         (master) 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
cmake is already the newest version.
libvlc-dev is already the newest version.
```

Im on 64bit btw..

**Comment by jaruba** [comment]
@RSATom any ideas of anything else that can cause that build error?

**Comment by RSATom** [comment]
@karserasl, check please, do you have this line
https://github.com/RSATom/WebChimera.js/blob/master/src/JsVlcVideo.h#L33
in your sources

**Comment by jaruba** [comment]
@karserasl could you please just delete the `node_modules` folder and do `npm install` again?

I did some magic and hopefully added `wcjs-prebuilt` successfully instead of `webchimera.js` which means that it should just download the prebuilt versions of `webchimera.js` and `vlc` now. (instead of trying to build webchimera.js)

**Comment by jaruba** [comment]
Updated building instructions: https://github.com/jaruba/PowderPlayer/wiki

**Comment by karserasl** [comment]
Sorry for late response.
Everything seems good.
I also build vlc from sources so dont know what did the trick but everything is working

Thanks for the help

**Comment by jaruba** [comment]
awesome :)
